// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package auth

import (
	"database/sql"
)

type Certificate struct {
	Pk                      int64
	UserEmail               interface{}
	SubjectCommonName       sql.NullString
	SubjectOrganization     interface{}
	SubjectOrganizationUnit interface{}
	SubjectCountry          interface{}
	SubjectLocality         interface{}
	SubjectProvince         interface{}
	IssuerID                sql.NullInt64
	SerialNumber            sql.NullString
	NotBefore               sql.NullString
	NotAfter                sql.NullString
}

type User struct {
	Pk       int64
	Email    sql.NullString
	Name     sql.NullString
	Password sql.NullString
	Uuid     sql.NullString
}
