### GET request to example server
GET http://localhost:6000/ping

###
POST http://localhost:6000/postping HTTP/1.1
Content-Type: application/json

{ "name":"Rolan", "email": "rolanvc@gmail.com"}


###
POST http://localhost:6000/get_server_cert HTTP/1.1
Content-Type: application/json

{"server":  "www.amazon.com"}

### Correct user, incorrect password
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@gmail.com", "password": "PASSWORD"}

### Correct user and password
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@gmail.com", "password": "<PASSWORD>"}

### Incorrect user
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@yahoo.com", "password": "<PASSWORD>"}


### Get Server Cert
POST http://localhost:5001/api/get_server_cert HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbGFudmNAZ21haWwuY29tIiwiZXhwIjoxNzUwNDMyNTM3LCJuYW1lIjoiUm9sYW5WQyJ9.Noxel_y0e5FTTYO6QugkcbzO14yv_hXN1eexlOEYoSU

{"server":"rolanvc.dev"}

### Get Server Cert
POST http://localhost:5001/api/get_server_cert HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbGFudmNAZ21haWwuY29tIiwiZXhwIjoxNzUwNDMyNTM3LCJuYW1lIjoiUm9sYW5WQyJ9.Noxel_y0e5FTTYO6QugkcbzO14yv_hXN1eexlOEYoSU

{"server":"www.amazon.com"}

### Get Certs, might need to login for a fresh/valid Token.
GET http://localhost:5001/api/get_certs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbGFudmNAZ21haWwuY29tIiwiZXhwIjoxNzUwMzIwMzg2LCJuYW1lIjoiUm9sYW5WQyJ9._nWRdk3q5zlt0RpMcOyFaFTXRcd-dRTkVg-mbdiLezQ
