### GET request to example server
GET http://localhost:6000/ping

###
POST http://localhost:6000/postping HTTP/1.1
Content-Type: application/json

{ "name":"Rolan", "email": "rolanvc@gmail.com"}


###
POST http://localhost:6000/get_server_cert HTTP/1.1
Content-Type: application/json

{"server":  "www.amazon.com"}

### Correct user, incorrect password
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@gmail.com", "password": "PASSWORD"}

### Correct user and password
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@gmail.com", "password": "<PASSWORD>"}

### Incorrect user
POST http://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{"email":  "rolanvc@yahoo.com", "password": "<PASSWORD>"}


### Get Server Cert
POST http://localhost:5001/api/get_server_cert HTTP/1.1

{"server":"www.amazon.com"}
