// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package certs

import (
	"database/sql"
)

type Certificate struct {
	Pk                        int64
	SqlTimeStamp              sql.NullTime
	UserEmail                 interface{}
	SubjectCommonName         sql.NullString
	SubjectOrganization       interface{}
	SubjectOrganizationalUnit interface{}
	SubjectCountry            interface{}
	SubjectLocality           interface{}
	SubjectProvince           interface{}
	IssuerCommonName          sql.NullString
	IssuerOrganization        sql.NullString
	IssuerOrganizationalUnit  sql.NullString
	IssuerCountry             sql.NullString
	SerialNumber              sql.NullString
	SignatureAlgorithm        sql.NullString
	PublicKeyAlgorithm        sql.NullString
	PublicKeySize             sql.NullInt64
	NotBefore                 sql.NullString
	NotAfter                  sql.NullString
	RequestedServer           interface{}
}
